name: Deploy Flutter to GitHub Pages

on:
  push:
    branches:
      - lab07-blinov-aleksandr

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        working-directory: ./labs/lab07/frontend
        run: flutter pub get

      - name: Build Flutter web app
        working-directory: ./labs/lab07/frontend
        run: |
          flutter create . --platforms web
          flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./labs/lab07/frontend/build/web
          publish_branch: gh-pages
